syntax = "proto3";

option java_package = "io.github.samolego.canta.data.proto";
option java_multiple_files = true;

message CantaPreset {
  string name = 1;
  string description = 2;
  int64 created_date = 3;
  repeated string apps = 4;
  string version = 5;
  string uuid = 6;
  repeated PresetLockdown lockdown = 7;
}

message PresetLockdown {
  string package_name = 1;
  bool revoke_permissions = 2;
  bool restrict_background = 3;
  bool deny_metered = 4;
  bool block_network = 5;
}

message PresetsList {
  repeated CantaPreset presets = 1;
}
